name: Publish Release

on:
  push:
    tags: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      with:
        distribution: corretto
        java-version: 11

    - uses: gradle/gradle-build-action@v2
      with:
        arguments: build

    - run: cd lib && zip -r ../wdk-federation-client.zip .

    - uses: softprops/action-gh-release@v1
      with:
        files: wdk-federation-client.zip
